import mongoose from 'mongoose';

export const properties = (agentId: mongoose.Types.ObjectId) => [
  {
    title: 'Modern 3BHK Apartment in Lazimpat',
    description: 'A spacious, sunlit apartment with panoramic mountain views and premium finishes throughout.',
    propertyType: 'apartment',
    listingType: 'sale',
    price: 12500000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: '14 Lazimpat Road',
      city: 'Kathmandu',
      district: 'Bagmati',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44600',
      coordinates: { lat: 27.7172, lng: 85.3240 },
    },
    bedrooms: 3,
    bathrooms: 2,
    area: 1450,
    areaUnit: 'sqft',
    floors: 5,
    yearBuilt: 2020,
    amenities: { pool: false, gym: true, parking: true, elevator: true, security: true, furnished: 'partial' },
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    isFeatured: true,
    views: 320,
    listedBy: agentId,
  },
  {
    title: 'Cozy Studio for Rent in Thamel',
    description: 'Fully furnished studio ideal for professionals or expats. Walking distance to restaurants and cafes.',
    propertyType: 'apartment',
    listingType: 'rent',
    price: 25000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Thamel Marg',
      city: 'Kathmandu',
      district: 'Bagmati',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44600',
      coordinates: { lat: 27.7154, lng: 85.3123 },
    },
    bedrooms: 0,
    bathrooms: 1,
    area: 380,
    areaUnit: 'sqft',
    yearBuilt: 2018,
    amenities: { pool: false, gym: false, parking: false, elevator: false, security: true, furnished: 'yes' },
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],
    isFeatured: false,
    views: 145,
    listedBy: agentId,
  },
  {
    title: 'Luxury Villa with Garden in Budhanilkantha',
    description: 'A grand 5-bedroom villa with private garden, imported marble flooring, and Himalayan views.',
    propertyType: 'villa',
    listingType: 'sale',
    price: 45000000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Budhanilkantha Road',
      city: 'Kathmandu',
      district: 'Bagmati',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44600',
      coordinates: { lat: 27.7779, lng: 85.3592 },
    },
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    areaUnit: 'sqft',
    floors: 3,
    yearBuilt: 2019,
    amenities: { pool: true, gym: true, parking: true, elevator: false, security: true, furnished: 'yes' },
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    isFeatured: true,
    views: 512,
    listedBy: agentId,
  },
  {
    title: '2BHK Apartment for Rent in Pulchowk',
    description: 'Semi-furnished apartment near Pulchowk Engineering Campus. Quiet neighborhood with easy road access.',
    propertyType: 'apartment',
    listingType: 'rent',
    price: 35000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Pulchowk Road',
      city: 'Lalitpur',
      district: 'Lalitpur',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44700',
      coordinates: { lat: 27.6771, lng: 85.3180 },
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    areaUnit: 'sqft',
    yearBuilt: 2016,
    amenities: { pool: false, gym: false, parking: true, elevator: false, security: true, furnished: 'partial' },
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    isFeatured: false,
    views: 98,
    listedBy: agentId,
  },
  {
    title: 'Commercial Space in New Baneshwor',
    description: 'Prime ground-floor commercial unit suitable for showroom, clinic, or office. High foot traffic area.',
    propertyType: 'commercial',
    listingType: 'rent',
    price: 80000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'New Baneshwor Chowk',
      city: 'Kathmandu',
      district: 'Bagmati',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44600',
      coordinates: { lat: 27.6933, lng: 85.3380 },
    },
    bedrooms: 0,
    bathrooms: 1,
    area: 1100,
    areaUnit: 'sqft',
    yearBuilt: 2015,
    amenities: { pool: false, gym: false, parking: true, elevator: false, security: true, furnished: 'no' },
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    isFeatured: false,
    views: 67,
    listedBy: agentId,
  },
  {
    title: 'Residential Land Plot in Bhaktapur',
    description: '5 ropani residential land with road access, close to Bhaktapur Durbar Square. Ideal for development.',
    propertyType: 'land',
    listingType: 'sale',
    price: 6000000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Suryamadhi Road',
      city: 'Bhaktapur',
      district: 'Bhaktapur',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44800',
      coordinates: { lat: 27.6722, lng: 85.4298 },
    },
    bedrooms: 0,
    bathrooms: 0,
    area: 17424,
    areaUnit: 'sqft',
    amenities: { pool: false, gym: false, parking: false, elevator: false, security: false, furnished: 'no' },
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    isFeatured: false,
    views: 44,
    listedBy: agentId,
  },
  {
    title: 'Penthouse Suite in Jhamsikhel',
    description: 'Top-floor penthouse with rooftop terrace, smart home system, and unobstructed city skyline views.',
    propertyType: 'apartment',
    listingType: 'sale',
    price: 32000000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Jhamsikhel Lane 4',
      city: 'Lalitpur',
      district: 'Lalitpur',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44700',
      coordinates: { lat: 27.6850, lng: 85.3172 },
    },
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    areaUnit: 'sqft',
    floors: 10,
    yearBuilt: 2022,
    amenities: { pool: true, gym: true, parking: true, elevator: true, security: true, furnished: 'yes' },
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800'],
    isFeatured: true,
    views: 740,
    listedBy: agentId,
  },
  {
    title: 'Affordable House for Sale in Kirtipur',
    description: 'Compact 2-storey house with courtyard, perfect for a starter family. Close to TU campus.',
    propertyType: 'house',
    listingType: 'sale',
    price: 7800000,
    currency: 'NPR',
    status: 'pending',
    location: {
      street: 'Kirtipur Bazar',
      city: 'Kirtipur',
      district: 'Bagmati',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44618',
      coordinates: { lat: 27.6774, lng: 85.2786 },
    },
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    areaUnit: 'sqft',
    floors: 2,
    yearBuilt: 2010,
    amenities: { pool: false, gym: false, parking: true, elevator: false, security: false, furnished: 'no' },
    images: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'],
    isFeatured: false,
    views: 211,
    listedBy: agentId,
  },
  {
    title: 'Office Space for Rent in Durbarmarg',
    description: 'Premium 3rd floor office in the heart of Kathmandu\'s business district. Glass facade, open layout.',
    propertyType: 'commercial',
    listingType: 'rent',
    price: 150000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Durbarmarg Avenue',
      city: 'Kathmandu',
      district: 'Bagmati',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44600',
      coordinates: { lat: 27.7109, lng: 85.3175 },
    },
    bedrooms: 0,
    bathrooms: 2,
    area: 2200,
    areaUnit: 'sqft',
    floors: 8,
    yearBuilt: 2017,
    amenities: { pool: false, gym: false, parking: true, elevator: true, security: true, furnished: 'partial' },
    images: ['https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800'],
    isFeatured: true,
    views: 403,
    listedBy: agentId,
  },
  {
    title: '1BHK Furnished Apartment in Sanepa',
    description: 'Bright, fully furnished 1BHK with balcony, close to international schools and supermarkets.',
    propertyType: 'apartment',
    listingType: 'rent',
    price: 30000,
    currency: 'NPR',
    status: 'active',
    location: {
      street: 'Sanepa Road',
      city: 'Lalitpur',
      district: 'Lalitpur',
      state: 'Bagmati Province',
      country: 'Nepal',
      zipCode: '44700',
      coordinates: { lat: 27.6921, lng: 85.3059 },
    },
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    areaUnit: 'sqft',
    yearBuilt: 2019,
    amenities: { pool: false, gym: false, parking: false, elevator: false, security: true, furnished: 'yes' },
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    isFeatured: false,
    views: 189,
    listedBy: agentId,
  },
];